### ISSUE TITLE
Cannot import as CJS/ES module.

### ISSUE THREAD

**Issue by moisadoru** [LoopFiftyFour/JS-Connector#2]
Currently, the library is published in built form, with no option to import as CommonJS/ESM module, without embedded axios, core-js and babel-polyfill, adding an extra 300Kb (200Kb minified), plus possible duplicate code because of the embedded libraries.

Created #1 for addressing this issue.

**Comment by joelwkall** [comment]
Should be fixed now that the PR is merged.
