### ISSUE TITLE
Upgrade Axios to v1.x

### ISSUE THREAD

**Issue by ristomatti** [LoopFiftyFour/JS-Connector#45]
After upgrading Axios to v1.1.3, I noticed it now gets duplicated on our bundle due to JS-Connector using an old version:
```sh
npm ls axios
redacted@1.0.0 /home/ristomatti/redacted
├── axios@1.1.3
└─┬ loop54-js-connector@1.9.128
  └── axios@0.21.4

**Comment by joelwkall** [comment]
Thanks, we'll discuss whether we want to upgrade it now or wait.

**Comment by lukethenuke** [comment]
In version 1.11

**Comment by ristomatti** [comment]
Thanks!
