### ISSUE TITLE
Length property typo causing certain calls to core.ensureProtocol(), core.validateEvent(), getLoop54Client() and client.createEvents() to have undesired behavior.

### ISSUE THREAD

**Issue by moisadoru** [LoopFiftyFour/JS-Connector#6]
Some checks for Strings or Arrays lengths improperly use the `.Length` property (with a capital `L`), when the correct property to check is `.length` (with a lowercase `l`), causing unexpected and unreliable behavior.

For example, calling `ensureProtocol('https://example.com/')` will return an empty string `''`.

A fix for this bug is available in #7.

**Comment by joelwkall** [comment]
This is now fixed by PR #7
