### ISSUE TITLE
lib/loop54-js-connector-client.js file is not transpiled with Babel

### ISSUE THREAD

**Issue by filmic** [LoopFiftyFour/JS-Connector#8]
The lib/loop54-js-connector-client.js file contains modern ES2018 syntax (object rest/spread operator) which is not supported by older browsers like Safari on iOS 11.2.

Example:
```
body = {
	...body
};
```

The package.json "build-client" task does not use Babel:
`"build-client": "rollup src/client.js -e axios -o lib/loop54-js-connector-client.js -f cjs",`

**Comment by joelwkall** [comment]
Hi, thank you for reporting this issue.

We used to use babel, but it was removed in commit https://github.com/LoopFiftyFour/JS-Connector/commit/a2afcf95bab23e323353ac1a74202bd32d4aaba9#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

We tested it before merging that PR but apparently did not test with old enough browsers.
Do you know exactly which browser versions you aim to support?

**Comment by joelwkall** [comment]
Wait no, that's not correct. We still use babel for the full connector, but not for the client.

**Comment by joelwkall** [comment]
After some discussion with @moisadoru we decided that the exported module should not be transpiled, rather this should be done by the importer. Added a notice about this in the README in https://github.com/LoopFiftyFour/JS-Connector/commit/5cf981834383d61d2fdda42857335dcdb7510609
